[pg_cluster]
ag-pg01-p1 ansible_host=10.110.20.11 pg_node_name=node1 etcd_name=etcd-01
ag-pg02-p1 ansible_host=10.110.20.12 pg_node_name=node2 etcd_name=etcd-02
ag-pg03-p1 ansible_host=10.110.20.13 pg_node_name=node3 etcd_name=etcd-03

[pg_primary]
ag-pg01-p1

[pg_replicas]
ag-pg02-p1
ag-pg03-p1

[pg_cluster:vars]
ansible_user=vapt_admin
ansible_become=true
ansible_ssh_private_key_file=/home/vapt_admin/.ssh/id_rsa
