---
# roles/configure_cluster/handlers/main.yml
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart patroni
  ansible.builtin.shell: |
    systemctl is-active --quiet patroni && systemctl restart patroni || true
  changed_when: false

- name: restart etcd
  ansible.builtin.shell: |
    systemctl is-active --quiet etcd && systemctl restart etcd || true
  changed_when: false

- name: restart keepalived
  ansible.builtin.shell: |
    systemctl is-active --quiet keepalived && systemctl restart keepalived || true
  changed_when: false
